In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score, confusion_matrix
from sklearn import svm
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('user_behavior_dataset.csv')
df

User ID        Device Model Operating System  App Usage Time (min/day)  \
0          1      Google Pixel 5          Android                       393   
1          2           OnePlus 9          Android                       268   
2          3        Xiaomi Mi 11          Android                       154   
3          4      Google Pixel 5          Android                       239   
4          5           iPhone 12              iOS                       187   
..       ...                 ...              ...                       ...   
695      696           iPhone 12              iOS                        92   
696      697        Xiaomi Mi 11          Android                       316   
697      698      Google Pixel 5          Android                        99   
698      699  Samsung Galaxy S21          Android                        62   
699      700           OnePlus 9          Android                       212   

     Screen On Time (hours/day)  Battery Drain (mAh/day)  \
0                           6.4                     1872   
1                           4.7                     1331   
2                           4.0                      761   
3                           4.8                     1676   
4                           4.3                     1367   
..                          ...                      ...   
695                         3.9                     1082   
696                         6.8                     1965   
697                         3.1                      942   
698                         1.7                      431   
699                         5.4                     1306   

     Number of Apps Installed  Data Usage (MB/day)  Age  Gender  \
0                          67                 1122   40    Male   
1                          42                  944   47  Female   
2                          32                  322   42    Male   
3                          56                  871   20    Male   
4                          58                  988   31  Female   
..                        ...                  ...  ...     ...   
695                        26                  381   22    Male   
696                        68                 1201   59    Male   
697                        22                  457   50  Female   
698                        13                  224   44    Male   
699                        49                  828   23  Female   

     User Behavior Class  
0                      4  
1                      3  
2                      2  
3                      3  
4                      3  
..                   ...  
695                    2  
696                    4  
697                    2  
698                    1  
699                    3  

[700 rows x 11 columns]

In [4]:
df.isnull().sum()

User ID                       0
Device Model                  0
Operating System              0
App Usage Time (min/day)      0
Screen On Time (hours/day)    0
Battery Drain (mAh/day)       0
Number of Apps Installed      0
Data Usage (MB/day)           0
Age                           0
Gender                        0
User Behavior Class           0
dtype: int64

In [8]:
df = df.drop(columns=["User ID"])

In [6]:
df

Device Model Operating System  App Usage Time (min/day)  \
0        Google Pixel 5          Android                       393   
1             OnePlus 9          Android                       268   
2          Xiaomi Mi 11          Android                       154   
3        Google Pixel 5          Android                       239   
4             iPhone 12              iOS                       187   
..                  ...              ...                       ...   
695           iPhone 12              iOS                        92   
696        Xiaomi Mi 11          Android                       316   
697      Google Pixel 5          Android                        99   
698  Samsung Galaxy S21          Android                        62   
699           OnePlus 9          Android                       212   

     Screen On Time (hours/day)  Battery Drain (mAh/day)  \
0                           6.4                     1872   
1                           4.7                     1331   
2                           4.0                      761   
3                           4.8                     1676   
4                           4.3                     1367   
..                          ...                      ...   
695                         3.9                     1082   
696                         6.8                     1965   
697                         3.1                      942   
698                         1.7                      431   
699                         5.4                     1306   

     Number of Apps Installed  Data Usage (MB/day)  Age  Gender  \
0                          67                 1122   40    Male   
1                          42                  944   47  Female   
2                          32                  322   42    Male   
3                          56                  871   20    Male   
4                          58                  988   31  Female   
..                        ...                  ...  ...     ...   
695                        26                  381   22    Male   
696                        68                 1201   59    Male   
697                        22                  457   50  Female   
698                        13                  224   44    Male   
699                        49                  828   23  Female   

     User Behavior Class  
0                      4  
1                      3  
2                      2  
3                      3  
4                      3  
..                   ...  
695                    2  
696                    4  
697                    2  
698                    1  
699                    3  

[700 rows x 10 columns]

In [9]:
labelencoder = LabelEncoder()
columns = ["Device Model", "Operating System", "Gender"]
for cols in columns:
  df[cols] = labelencoder.fit_transform(df[cols])

In [10]:
df

Device Model  Operating System  App Usage Time (min/day)  \
0               0                 0                       393   
1               1                 0                       268   
2               3                 0                       154   
3               0                 0                       239   
4               4                 1                       187   
..            ...               ...                       ...   
695             4                 1                        92   
696             3                 0                       316   
697             0                 0                        99   
698             2                 0                        62   
699             1                 0                       212   

     Screen On Time (hours/day)  Battery Drain (mAh/day)  \
0                           6.4                     1872   
1                           4.7                     1331   
2                           4.0                      761   
3                           4.8                     1676   
4                           4.3                     1367   
..                          ...                      ...   
695                         3.9                     1082   
696                         6.8                     1965   
697                         3.1                      942   
698                         1.7                      431   
699                         5.4                     1306   

     Number of Apps Installed  Data Usage (MB/day)  Age  Gender  \
0                          67                 1122   40       1   
1                          42                  944   47       0   
2                          32                  322   42       1   
3                          56                  871   20       1   
4                          58                  988   31       0   
..                        ...                  ...  ...     ...   
695                        26                  381   22       1   
696                        68                 1201   59       1   
697                        22                  457   50       0   
698                        13                  224   44       1   
699                        49                  828   23       0   

     User Behavior Class  
0                      4  
1                      3  
2                      2  
3                      3  
4                      3  
..                   ...  
695                    2  
696                    4  
697                    2  
698                    1  
699                    3  

[700 rows x 10 columns]

In [11]:
X = df.drop(columns=["User Behavior Class"])
y = df["User Behavior Class"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)


In [21]:
model = svm.SVC(kernel='poly')
model.fit(X_train, y_train)

SVC(kernel='poly')

In [22]:
y_pred = model.predict(X_test)

In [23]:
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Precision: {precision_score(y_test, y_pred, average='weighted')}")
print(f"Recall: {recall_score(y_test, y_pred, average='weighted')}")
print(f"F1: {f1_score(y_test, y_pred, average='weighted')}")


Accuracy: 0.9314285714285714
Precision: 0.9493167701863353
Recall: 0.9314285714285714
F1: 0.9294778325123153


In [28]:
df

Device Model  Operating System  App Usage Time (min/day)  \
0               0                 0                       393   
1               1                 0                       268   
2               3                 0                       154   
3               0                 0                       239   
4               4                 1                       187   
..            ...               ...                       ...   
695             4                 1                        92   
696             3                 0                       316   
697             0                 0                        99   
698             2                 0                        62   
699             1                 0                       212   

     Screen On Time (hours/day)  Battery Drain (mAh/day)  \
0                           6.4                     1872   
1                           4.7                     1331   
2                           4.0                      761   
3                           4.8                     1676   
4                           4.3                     1367   
..                          ...                      ...   
695                         3.9                     1082   
696                         6.8                     1965   
697                         3.1                      942   
698                         1.7                      431   
699                         5.4                     1306   

     Number of Apps Installed  Data Usage (MB/day)  Age  Gender  \
0                          67                 1122   40       1   
1                          42                  944   47       0   
2                          32                  322   42       1   
3                          56                  871   20       1   
4                          58                  988   31       0   
..                        ...                  ...  ...     ...   
695                        26                  381   22       1   
696                        68                 1201   59       1   
697                        22                  457   50       0   
698                        13                  224   44       1   
699                        49                  828   23       0   

     User Behavior Class  
0                      4  
1                      3  
2                      2  
3                      3  
4                      3  
..                   ...  
695                    2  
696                    4  
697                    2  
698                    1  
699                    3  

[700 rows x 10 columns]

In [30]:
device = int(input("Enter device model: "))
os = int(input("Enter OS: "))
app = int(input("Enter App Usage Time: "))
sot = float(input("Enter App Usage Time: "))
bd = int(input("Battery Drain: "))
apps = int(input("Enter Apps: "))
data = int(input("Enter Data Usage Time: "))
age = int(input("EnterAge: "))
gender = int(input("Enter gender: "))

newdf = np.array([[device, os, app, sot, bd, apps, data, age, gender]])
newpred = model.predict(newdf)

print(newpred[0])

Enter device model: 1
Enter OS: 1
Enter App Usage Time: 23
Enter App Usage Time: 5.6
Battery Drain: 4000
Enter Apps: 43
Enter Data Usage Time: 1000
EnterAge: 20
Enter gender: 1
5


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [32]:
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score, confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[34  0  0  0  0]
 [12 23  0  0  0]
 [ 0  0 36  0  0]
 [ 0  0  0 38  0]
 [ 0  0  0  0 32]]
